services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: memo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: memo_auth
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 5s
      retries: 5

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: memo-auth
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: memo_auth
    ports:
      - "50051:50051"

volumes:
  mysql_data:
